# Generated by Django 4.2.5 on 2024-06-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_email_estudiante_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='estudiantes',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecharegistro',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.estudiante'),
            preserve_default=False,
        ),
    ]
